// Generated by dts-bundle-generator v5.9.0

/// <reference types="node" />

export declare type Locale = {
	code?: string;
	formatDistance?: (...args: Array<any>) => any;
	formatRelative?: (...args: Array<any>) => any;
	localize?: {
		ordinalNumber: (...args: Array<any>) => any;
		era: (...args: Array<any>) => any;
		quarter: (...args: Array<any>) => any;
		month: (...args: Array<any>) => any;
		day: (...args: Array<any>) => any;
		dayPeriod: (...args: Array<any>) => any;
	};
	formatLong?: {
		date: (...args: Array<any>) => any;
		time: (...args: Array<any>) => any;
		dateTime: (...args: Array<any>) => any;
	};
	match?: {
		ordinalNumber: (...args: Array<any>) => any;
		era: (...args: Array<any>) => any;
		quarter: (...args: Array<any>) => any;
		month: (...args: Array<any>) => any;
		day: (...args: Array<any>) => any;
		dayPeriod: (...args: Array<any>) => any;
	};
	options?: {
		weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
		firstWeekContainsDate?: 1 | 2 | 3 | 4 | 5 | 6 | 7;
	};
};
export function compareAsc(dateLeft: Date | number, dateRight: Date | number): number;
export function format(date: Date | number, format: string, options?: {
	locale?: Locale;
	weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
	firstWeekContainsDate?: number;
	useAdditionalWeekYearTokens?: boolean;
	useAdditionalDayOfYearTokens?: boolean;
}): string;
export function formatDistanceToNow(date: Date | number, options?: {
	includeSeconds?: boolean;
	addSuffix?: boolean;
	locale?: Locale;
}): string;
export function formatDistanceToNowStrict(date: Date | number, options?: {
	addSuffix?: boolean;
	unit?: "second" | "minute" | "hour" | "day" | "month" | "year";
	roundingMethod?: "floor" | "ceil" | "round";
	locale?: Locale;
}): string;
export function parseISO(argument: string, options?: {
	additionalDigits?: 0 | 1 | 2;
}): Date;
export namespace compareAsc { }
export namespace format { }
export namespace formatDistanceToNow { }
export namespace formatDistanceToNowStrict { }
export namespace parseISO { }

export {};
