// Generated by dts-bundle-generator v5.9.0

export declare class JSONFile<T> implements Adapter<T> {
	#private;
	constructor(filename: string);
	read(): Promise<T | null>;
	write(obj: T): Promise<void>;
}
export declare class Low<T = unknown> {
	adapter: Adapter<T>;
	data: T | null;
	constructor(adapter: Adapter<T>);
	read(): Promise<void>;
	write(): Promise<void>;
}
export interface Adapter<T> {
	read: () => Promise<T | null>;
	write: (data: T) => Promise<void>;
}

export {};
