// Generated by dts-bundle-generator v5.9.0

export declare const Octokit: typeof OctokitCore & import("@octokit/core/dist-types/types").Constructor<void & {
	paginate: import("@octokit/plugin-paginate-rest").PaginateInterface;
} & import("@octokit/plugin-rest-endpoint-methods/dist-types/types").Api>;

export {};
